server:
  port: 8761


eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
#  server:
#    enable-self-preservation: true
#  server:
#    waitTimeInMsWhenSyncEmpty: 0

